In [1]:
import numpy as np

def idx(i, j, n):
    return i * n + j

def montar_sistema(n, topo, base, esquerda, direita):
    N = n * n
    A = np.zeros((N, N))
    b = np.zeros(N)

    for i in range(n):
        for j in range(n):
            k = idx(i, j, n)

            A[k, k] = 4

            # cima
            if i > 0:
                A[k, idx(i-1, j, n)] = -1
            else:
                b[k] += topo[j]

            # baixo
            if i < n - 1:
                A[k, idx(i+1, j, n)] = -1
            else:
                b[k] += base[j]

            # esquerda
            if j > 0:
                A[k, idx(i, j-1, n)] = -1
            else:
                b[k] += esquerda[i]

            # direita
            if j < n - 1:
                A[k, idx(i, j+1, n)] = -1
            else:
                b[k] += direita[i]

    return A, b


n = 3

topo = [100, 100, 100]
base = [0, 0, 0]
esquerda = [75, 75, 75]
direita = [50, 50, 50]

A, b = montar_sistema(n, topo, base, esquerda, direita)

x = np.linalg.solve(A, b)

resultado = x.reshape((n, n))

print("Temperaturas internas:")
print(resultado)

Temperaturas internas:
[[78.57142857 76.11607143 69.64285714]
 [63.16964286 56.25       52.45535714]
 [42.85714286 33.25892857 33.92857143]]
